package dev.rodrigosambade.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class DemoDatabase {

    private static final String DEFAULT_URL = "jdbc:h2:mem:tienda;DB_CLOSE_DELAY=-1";
    private static final String DEFAULT_USER = "sa";

    private DemoDatabase() {
    }

    public static Connection open() throws SQLException {
        Connection connection = DriverManager.getConnection(
                System.getProperty("db.url", DEFAULT_URL),
                System.getProperty("db.user", DEFAULT_USER),
                System.getProperty("db.password", ""));

        initializeSchema(connection);
        seedReferenceData(connection);
        seedArticlesIfEmpty(connection);
        return connection;
    }

    private static void initializeSchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS marcas (
                        codigo INT PRIMARY KEY,
                        nombre VARCHAR(80) NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS familias (
                        codigo INT PRIMARY KEY,
                        nombre VARCHAR(80) NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS articulos (
                        codigo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        modelo VARCHAR(120) NOT NULL,
                        descripcion VARCHAR(500),
                        precio DECIMAL(12,2) NOT NULL CHECK (precio >= 0),
                        descuento DECIMAL(5,2) DEFAULT 0,
                        cod_marca INT REFERENCES marcas(codigo),
                        cod_familia INT REFERENCES familias(codigo)
                    )
                    """);
        }
    }

    private static void seedReferenceData(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(
                    "MERGE INTO marcas KEY(codigo) VALUES (1, 'Acme'), (2, 'TESDAI')");
            statement.executeUpdate(
                    "MERGE INTO familias KEY(codigo) VALUES (1, 'General'), (2, 'Informática')");
        }
    }

    private static void seedArticlesIfEmpty(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) FROM articulos")) {
            resultSet.next();
            if (resultSet.getInt(1) != 0) {
                return;
            }
        }

        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    INSERT INTO articulos (
                        modelo, descripcion, precio, descuento, cod_marca, cod_familia
                    ) VALUES
                        ('Modelo A', 'Artículo de demostración', 99.95, 0, 1, 1),
                        ('Portátil X', 'Equipo de demostración', 799.00, 5, 2, 2)
                    """);
        }
    }
}
