package dev.rodrigosambade.jdbc;
import java.sql.*;
public final class DemoDatabase {
    private DemoDatabase() {}
    public static Connection open() throws SQLException {
        Connection c = DriverManager.getConnection(System.getProperty("db.url", "jdbc:h2:mem:tienda;DB_CLOSE_DELAY=-1"), System.getProperty("db.user", "sa"), System.getProperty("db.password", ""));
        try (Statement s = c.createStatement()) {
            s.execute("create table if not exists marcas(codigo int primary key, nombre varchar(80) not null)");
            s.execute("create table if not exists familias(codigo int primary key, nombre varchar(80) not null)");
            s.execute("create table if not exists articulos(codigo int generated by default as identity primary key, modelo varchar(120) not null, descripcion varchar(500), precio decimal(12,2) not null check(precio>=0), descuento decimal(5,2) default 0, cod_marca int references marcas(codigo), cod_familia int references familias(codigo))");
            s.executeUpdate("merge into marcas key(codigo) values(1,'Acme'),(2,'TESDAI')");
            s.executeUpdate("merge into familias key(codigo) values(1,'General'),(2,'Informática')");
            try (ResultSet rs = s.executeQuery("select count(*) from articulos")) {
                rs.next();
                if (rs.getInt(1)==0) s.executeUpdate("insert into articulos(modelo,descripcion,precio,descuento,cod_marca,cod_familia) values('Modelo A','Artículo de demostración',99.95,0,1,1),('Portátil X','Equipo de demostración',799.00,5,2,2)");
            }
        }
        return c;
    }
}
